language: nodejs
node_js: 
  - lts/*
env:
  matrix:
    - HUGO_VERSION="0.55.5"
    - HUGO_VERSION="0.55.6"
  # global:
  #   - PUBLISH_DIR="docs"
  #   - THEMES_DIR="../.."

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - mv hugo ~/bin/
  - hugo version

notifications:
email:
  recipients:
    - ej.mason@pearson.com
  on_success: never
  on_failure: always