env:
  matrix:
    - HUGO_VERSION="0.55.5"
    - HUGO_VERSION="0.55.6"
  global:
    - PUBLISH_DIR="docs"
    - THEMES_DIR="../.."

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - mv hugo ~/bin/
  - hugo version
  - gem install html-proofer
  - htmlproofer --version
  - git clone https://github.com/EmielH/hugo-theme-test.git

script: |
  cd hugo-theme-test
  hugo -t learner --themesDir ${THEMES_DIR}
  htmlproofer ${PUBLISH_DIR} --check-html --disable-external --allow-hash-href --checks-to-ignore LinkCheck

notifications:
email:
  recipients:
    - ej.mason@pearson.com
  on_success: never
  on_failure: always