language: node_js
node_js: 
  - lts/*
cache: npm
env:
  matrix:
    - HUGO_VERSION="0.55.5"
    - HUGO_VERSION="0.55.6"
  # global:
  #   - PUBLISH_DIR="docs"
  #   - THEMES_DIR="../.."

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - mv hugo ~/bin/
  - hugo version
script: |
  npm run serve &
  npm test
notifications:
email:
  recipients:
    - ej.mason@pearson.com
  on_success: never
  on_failure: always

  deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master